# Generated by Django 5.0.7 on 2024-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('ano_lancamento', models.IntegerField(default=0)),
                ('duracao', models.CharField(max_length=4)),
                ('url_img', models.CharField(max_length=200)),
            ],
        ),
    ]
