# Generated by Django 5.0.6 on 2024-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='situacao',
            field=models.CharField(default='digital', max_length=10),
            preserve_default=False,
        ),
    ]
