# Generated by Django 5.0.6 on 2024-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_ano_lancamento_filme_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='data_lancamento',
            field=models.CharField(max_length=30),
        ),
    ]
