# Generated by Django 5.0.6 on 2024-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_filme_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='url_img',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
