# Generated by Django 5.0.6 on 2024-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_filme_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='url_img',
            field=models.TextField(default='default_image_url.jpg'),
        ),
    ]
