# Generated by Django 5.0.6 on 2024-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_filme_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='url_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
